
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Chathura
 */
public class Login_Page extends javax.swing.JFrame {
        Connection conn=null;
	 ResultSet rs=null;
	 PreparedStatement pst=null;
    /**
     * Creates new form Login
     */
    public Login_Page() {
        initComponents();
         conn=DBConnection.connectDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_Login_Page = new javax.swing.JPanel();
        jLabel_Login_Page_username = new javax.swing.JLabel();
        jLabel_Login_Panel_password = new javax.swing.JLabel();
        jButton_Login_Page_Login_Button = new javax.swing.JButton();
        jButton_Login_Page_Create_New_Account = new javax.swing.JButton();
        jButton_Login_Page_Exit_Button = new javax.swing.JButton();
        jButton_Login_Page_Forgot_Account_Button = new javax.swing.JButton();
        username_txt = new javax.swing.JTextField();
        password_txt = new javax.swing.JPasswordField();
        jButton_Login_Page_Contact_Me = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Login_Page.setBorder(javax.swing.BorderFactory.createTitledBorder("ss"));
        jPanel_Login_Page.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Login_Page_username.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        jLabel_Login_Page_username.setText("Username : ");
        jPanel_Login_Page.add(jLabel_Login_Page_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        jLabel_Login_Panel_password.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        jLabel_Login_Panel_password.setText("Password : ");
        jPanel_Login_Page.add(jLabel_Login_Panel_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 61, -1, 30));

        jButton_Login_Page_Login_Button.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        jButton_Login_Page_Login_Button.setText("Login");
        jButton_Login_Page_Login_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Login_Page_Login_ButtonActionPerformed(evt);
            }
        });
        jButton_Login_Page_Login_Button.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_Login_Page_Login_ButtonKeyPressed(evt);
            }
        });
        jPanel_Login_Page.add(jButton_Login_Page_Login_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 105, 233, -1));

        jButton_Login_Page_Create_New_Account.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        jButton_Login_Page_Create_New_Account.setText("Create a New Account");
        jButton_Login_Page_Create_New_Account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Login_Page_Create_New_AccountActionPerformed(evt);
            }
        });
        jPanel_Login_Page.add(jButton_Login_Page_Create_New_Account, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 187, -1, -1));

        jButton_Login_Page_Exit_Button.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        jButton_Login_Page_Exit_Button.setText("Exit");
        jButton_Login_Page_Exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Login_Page_Exit_ButtonActionPerformed(evt);
            }
        });
        jPanel_Login_Page.add(jButton_Login_Page_Exit_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 269, 233, -1));

        jButton_Login_Page_Forgot_Account_Button.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        jButton_Login_Page_Forgot_Account_Button.setText("Forgot account ?");
        jButton_Login_Page_Forgot_Account_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Login_Page_Forgot_Account_ButtonActionPerformed(evt);
            }
        });
        jPanel_Login_Page.add(jButton_Login_Page_Forgot_Account_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 146, 233, -1));

        username_txt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel_Login_Page.add(username_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 15, 120, 35));

        password_txt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel_Login_Page.add(password_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 64, 120, 35));

        jButton_Login_Page_Contact_Me.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        jButton_Login_Page_Contact_Me.setText("Contact Me");
        jButton_Login_Page_Contact_Me.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Login_Page_Contact_MeActionPerformed(evt);
            }
        });
        jPanel_Login_Page.add(jButton_Login_Page_Contact_Me, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 228, 233, -1));

        jPanel1.add(jPanel_Login_Page, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 310, 360));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Login_Page_Login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Login_Page_Login_ButtonActionPerformed
        // TODO add your handling code here:
    String sql = "SELECT * FROM passbox_db.users_tb where username=? and password=?;";
        try {
            pst=conn.prepareStatement(sql);
            pst.setString(1, username_txt.getText());
            pst.setString(2, password_txt.getText());
            rs=pst.executeQuery();
            if(rs.next()){
              JOptionPane.showMessageDialog(null,"Login Successfully!");
                this.setVisible(false);
                Home frame = new Home();
                frame.setVisible(true);
            }
            else{
            JOptionPane.showMessageDialog(null,"Login UnSuccessfully!");
            }
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(null, "Check Username and Password!");
        }
        

    }//GEN-LAST:event_jButton_Login_Page_Login_ButtonActionPerformed

    private void jButton_Login_Page_Create_New_AccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Login_Page_Create_New_AccountActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        create_account frame = new create_account();
        frame.setVisible(true);

    }//GEN-LAST:event_jButton_Login_Page_Create_New_AccountActionPerformed

    private void jButton_Login_Page_Exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Login_Page_Exit_ButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton_Login_Page_Exit_ButtonActionPerformed

    private void jButton_Login_Page_Forgot_Account_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Login_Page_Forgot_Account_ButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        forgot frame = new forgot();
        frame.setVisible(true);
    }//GEN-LAST:event_jButton_Login_Page_Forgot_Account_ButtonActionPerformed

    private void jButton_Login_Page_Contact_MeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Login_Page_Contact_MeActionPerformed
        // TODO add your handling code here:
        contact_me frame = new contact_me();
        frame.setVisible(true);
    }//GEN-LAST:event_jButton_Login_Page_Contact_MeActionPerformed

    private void jButton_Login_Page_Login_ButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_Login_Page_Login_ButtonKeyPressed
       if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            String sql = "SELECT * FROM passbox_db.users_tb where username=? and password=?;";
        try {
            pst=conn.prepareStatement(sql);
            pst.setString(1, username_txt.getText());
            pst.setString(2, password_txt.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(null,"Login Successfully!");
                this.setVisible(false);
                Home frame = new Home();
                frame.setVisible(true);
            }
            else{
            JOptionPane.showMessageDialog(null,"Login UnSuccessfully!");
            }
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(null, "Check Username and Password!");
        }
        }
    }//GEN-LAST:event_jButton_Login_Page_Login_ButtonKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Login_Page_Contact_Me;
    private javax.swing.JButton jButton_Login_Page_Create_New_Account;
    private javax.swing.JButton jButton_Login_Page_Exit_Button;
    private javax.swing.JButton jButton_Login_Page_Forgot_Account_Button;
    private javax.swing.JButton jButton_Login_Page_Login_Button;
    private javax.swing.JLabel jLabel_Login_Page_username;
    private javax.swing.JLabel jLabel_Login_Panel_password;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Login_Page;
    private javax.swing.JPasswordField password_txt;
    private javax.swing.JTextField username_txt;
    // End of variables declaration//GEN-END:variables
}
