
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Chathura
 */
public class Login_Page extends javax.swing.JFrame {
        Connection conn=null;
	 ResultSet rs=null;
	 PreparedStatement pst=null;
    /**
     * Creates new form Login
     */
    public Login_Page() {
        initComponents();
         conn=DBConnection.connectDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_Login_Page_username = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton_Login_Page_Create_New_Account = new javax.swing.JButton();
        jButton_Login_Page_Forgot_Account_Button = new javax.swing.JLabel();
        password_txt = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        rSLabelImage2 = new rojerusan.RSLabelImage();
        jLabel_Login_Panel_password = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        username_txt = new javax.swing.JTextField();
        rSLabelImage3 = new rojerusan.RSLabelImage();
        rSLabelImage1 = new rojerusan.RSLabelImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Login_Page_username.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel_Login_Page_username.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Login_Page_username.setText("Username : ");
        jPanel1.add(jLabel_Login_Page_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jButton1.setBackground(new java.awt.Color(11, 32, 37));
        jButton1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGIN");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 0, 0)));
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 230, 30));

        jButton_Login_Page_Create_New_Account.setBackground(new java.awt.Color(11, 32, 37));
        jButton_Login_Page_Create_New_Account.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jButton_Login_Page_Create_New_Account.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Login_Page_Create_New_Account.setText("Register");
        jButton_Login_Page_Create_New_Account.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 0, 0)));
        jButton_Login_Page_Create_New_Account.setOpaque(false);
        jButton_Login_Page_Create_New_Account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Login_Page_Create_New_AccountActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Login_Page_Create_New_Account, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 230, 30));

        jButton_Login_Page_Forgot_Account_Button.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 1, 14)); // NOI18N
        jButton_Login_Page_Forgot_Account_Button.setForeground(new java.awt.Color(255, 0, 0));
        jButton_Login_Page_Forgot_Account_Button.setText("Forgot Password ?");
        jButton_Login_Page_Forgot_Account_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Login_Page_Forgot_Account_ButtonMouseClicked(evt);
            }
        });
        jPanel1.add(jButton_Login_Page_Forgot_Account_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        password_txt.setBackground(new java.awt.Color(11, 32, 37));
        password_txt.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        password_txt.setForeground(new java.awt.Color(255, 255, 255));
        password_txt.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 0, 0)));
        jPanel1.add(password_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 230, 30));

        jLabel1.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("If  Your New Create Account");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        rSLabelImage2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(111, 254, 255))); // NOI18N
        rSLabelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/1607592763738.png"))); // NOI18N
        jPanel1.add(rSLabelImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 110, 110));

        jLabel_Login_Panel_password.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel_Login_Panel_password.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Login_Panel_password.setText("Password : ");
        jPanel1.add(jLabel_Login_Panel_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("x");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 20, 30));

        username_txt.setBackground(new java.awt.Color(11, 32, 37));
        username_txt.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        username_txt.setForeground(new java.awt.Color(255, 255, 255));
        username_txt.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 0, 0)));
        username_txt.setOpaque(false);
        jPanel1.add(username_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 230, 30));

        rSLabelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/1607591829931.jpg"))); // NOI18N
        jPanel1.add(rSLabelImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 270, 510));

        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/1607591593769.png"))); // NOI18N
        jPanel1.add(rSLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Login_Page_Forgot_Account_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Login_Page_Forgot_Account_ButtonMouseClicked
        this.setVisible(false);
        forgot frame = new forgot();
        frame.setVisible(true);
    }//GEN-LAST:event_jButton_Login_Page_Forgot_Account_ButtonMouseClicked

    private void jButton_Login_Page_Create_New_AccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Login_Page_Create_New_AccountActionPerformed
        this.setVisible(false);
        create_account frame = new create_account();
        frame.setVisible(true);
    }//GEN-LAST:event_jButton_Login_Page_Create_New_AccountActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String sql = "SELECT * FROM passbox_db.users_tb where username=? and password=?;";
        try {
            pst=conn.prepareStatement(sql);
            pst.setString(1, username_txt.getText());
            pst.setString(2, password_txt.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(null,"Login Successfully!");
                this.setVisible(false);
                Home frame = new Home();
                frame.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null,"Login UnSuccessfully!");
            }
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(null, "Check Username and Password!");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Login_Page_Create_New_Account;
    private javax.swing.JLabel jButton_Login_Page_Forgot_Account_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_Login_Page_username;
    private javax.swing.JLabel jLabel_Login_Panel_password;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password_txt;
    private rojerusan.RSLabelImage rSLabelImage1;
    private rojerusan.RSLabelImage rSLabelImage2;
    private rojerusan.RSLabelImage rSLabelImage3;
    private javax.swing.JTextField username_txt;
    // End of variables declaration//GEN-END:variables
}
