
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Chathura
 */
public class new_pass extends javax.swing.JFrame {
Connection conn=null;
	 ResultSet rs=null;
	 PreparedStatement pst=null;
    /**
     * Creates new form new_pass
     */
    public new_pass() {
        initComponents();
        conn=DBConnection.connectDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_socail_media_name = new javax.swing.JLabel();
        socail_media_name_txt = new javax.swing.JTextField();
        jLabel_username = new javax.swing.JLabel();
        username_txt = new javax.swing.JTextField();
        jLabel_password = new javax.swing.JLabel();
        password_txt = new javax.swing.JTextField();
        jLabel_email_address = new javax.swing.JLabel();
        email_address_txt = new javax.swing.JTextField();
        jButton_TurnBack = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_socail_media_name.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_socail_media_name.setText("Social Media Name : ");
        jPanel1.add(jLabel_socail_media_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        socail_media_name_txt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(socail_media_name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 147, 205, -1));

        jLabel_username.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_username.setText("Username : ");
        jPanel1.add(jLabel_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 176, -1, -1));

        username_txt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(username_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 173, 205, -1));

        jLabel_password.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_password.setText("Password : ");
        jPanel1.add(jLabel_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 202, -1, -1));

        password_txt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(password_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 199, 205, -1));

        jLabel_email_address.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_email_address.setText("E-Mail Address : ");
        jPanel1.add(jLabel_email_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 228, -1, -1));

        email_address_txt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(email_address_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 225, 205, -1));

        jButton_TurnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_TurnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/turnback_ico.png"))); // NOI18N
        jButton_TurnBack.setText("Turn Back");
        jButton_TurnBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_TurnBack.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_TurnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TurnBackActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_TurnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 312, 151, 90));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/add_new_password_ico.png"))); // NOI18N
        jButton1.setText("New Password Add");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 312, 166, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_TurnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TurnBackActionPerformed
        // TODO add your handling code here:
        Home ad = new Home ();
         ad.setVisible(true);
         this.dispose();
        
    }//GEN-LAST:event_jButton_TurnBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sql = "INSERT INTO `passbox_db`.`password_database_tb`(`account_name`,`username`,`password`,`email_address`)VALUES(?,?,?,?)";
        try {
            pst=conn.prepareStatement(sql);
            pst.setString(1, socail_media_name_txt.getText());
            pst.setString(2, username_txt.getText());
            pst.setString(3, password_txt.getText());
            pst.setString(4, email_address_txt.getText());
            int x= pst.executeUpdate();
            if(x==1)
            JOptionPane.showMessageDialog(null,"New Password Added Sucessfully");
            else
            JOptionPane.showMessageDialog(null,"error");
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(null, "error !"+ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(new_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(new_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(new_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(new_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new new_pass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email_address_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_TurnBack;
    private javax.swing.JLabel jLabel_email_address;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JLabel jLabel_socail_media_name;
    private javax.swing.JLabel jLabel_username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField password_txt;
    private javax.swing.JTextField socail_media_name_txt;
    private javax.swing.JTextField username_txt;
    // End of variables declaration//GEN-END:variables
}
